import type { Metadata } from "next"
import { Cairo } from "next/font/google"
import "./globals.css"
import Providers from "@/components/Providers"
import { dashboardLinks } from "@/constants"
import Sidebar from "@/components/sidebar"
import SidebarHeader from "@/components/SidebarHeader"
import DashboardHeader from "@/components/DashboardHeader"

const cairo = Cairo({ subsets: ["latin", "arabic"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cairo.className}>
        <Providers>
          <SidebarHeader />
          <main className="md:h-screen md:overflow-auto md:grid md:grid-cols-[250px_1fr] dashboard">
            <Sidebar
              sidebarProps={{
                className: "",
              }}
              title="elaf-dashboard"
              items={dashboardLinks}
            />
            <div>
              <DashboardHeader />
              <div className="container py-4 bg-light-blue dark:bg-primary-dark screen-minus-headers overflow-auto">
                <div className="">{children}</div>
              </div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
